### PR TITLE
Validation for "invalid data" that cannot be saved + refactoring

### LINKED ISSUE #1749: Invalid data in data model should show up as validation errors to the user
In the v4-rc1, if you type something into a field that doesn't validate according to the JsonSchema basic data type (such as typing something other than `true` or `false` in a field bound to a `boolean` in the data model, or typing `-` or a very large number in a `number` or `integer` field) the data will just not be saved anywhere, and you'll lose that data without any warning. In v3, it would cause a backend error, as we'd pass a string that wasn't possible to deserialize.

Before releasing v4 stable, we should implement a new validation class for these problems. This sounds like it should be possible via the current `JsonSchema` validation, but it's not - it's not really that the values are not valid according to JsonSchema, it's errors where data cannot be cast to their respective types (it's impossible to cast `-` to a number without turning it into `-0`, but `-` is the start of any negative number). The same goes for very large (positive or negative) numbers, which we assume won't be possible to cast to `decimal` or `int32` in C#, and therefore are marked as invalid.

As this data cannot be saved at all until valid, it breaks with the model that refreshing the page should re-introduce all the same validation messages.

Right now, we assume that all fields marked as `numeric` in JsonSchema maps to `decimal` in C#, and all fields marked as `integer` in JsonSchema maps to `int`/`int32` in C#, along with their respective range of valid values. We might want to support using a hint in JsonSchema to map to the real type used in the C# model instead.

See these links for C# data types:
- https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types
- https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types

### Related issue(s)
- https://github.com/Altinn/app-lib-dotnet/issues/197
- https://github.com/Altinn/app-lib-dotnet/issues/134
- https://altinndevops.slack.com/archives/C045EB3JA9X/p1706629447618599?thread_ts=1706627814.812689&cid=C045EB3JA9X

### LINKED ISSUE #1847: Refreshing expression validation configuration
The current configuration for expression validation works as-is, but is suboptimal after the more recent changes to how single field validation and backend validation works (on save, no more `*FIXED*`). Before releasing the feature fully, and releasing the documentation for it, we should look over the configuration format and adjust it to more closely match (and work like) the newer validation logic works.

### LINKED ISSUE #1848: Backend validation groups are "forgotten" if not included in every request
### Description of the bug

The `useBackendValidation` no longer keeps track of the validation groups through incremental validation. It now only checks the initialValidations and the last validated validationgroups causing it to forget previous incremental validations if they are not included in each request.

### Steps To Reproduce

1. Implement a custom validator in the backend with a `HasRelevantChanges` implementation that only runs when a specific field changes.
2. Notice that if any other field is changed, any validations from this group disappear.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by bjosttveit**
## Description

- This adds support for validating the contents of the `invalidData` object to give feedback to the user when data is not able to be stored in the strongly typed models in the app backend. https://github.com/Altinn/app-frontend-react/issues/1776 Adds proper support for more data types and should work with this.
- Fixes backend validation being broken by forgetting previous incremental validations
- Expression validations are now always run, meaning that there should not be any "field dependency" issues.
- I refactored most of the validation logic to align more with the structures introduced in invalid data validation. In my opinion the validation logic is much simpler and easier to read. And most likely less error-prone. Possibly at some performance cost, however it is hard to say exactly, as the checks it previously had to do to avoid unecessary validation before was a bit expensive.
- This refactor resolves a potential edge-case from the Datepicker format validation conflict. Schema validation should not be much less efficient, as the entire schema had to be validated before as well.

## Related Issue(s)

- closes #1749 
- closes #1848 
- closes #1847 

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [x] Unit test(s) have been added/updated
  - [x] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [x] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [x] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [x] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

File: src/features/validation/invalidDataValidation/useInvalidDataValidation.ts [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+
+export function useInvalidDataValidation(): FieldValidations {
+  const invalidData = FD.useInvalidDebounced();
+
+  return useMemo(() => {
+    if (Object.keys(invalidData).length === 0) {
+      return __default__;
+    }
+
+    return Object.keys(dot.dot(invalidData)).reduce((validations, field) => {
```
Comment (olemartinorg) [inline src/features/validation/invalidDataValidation/useInvalidDataValidation.ts:19]: Hmm, I would think it's possible for the invalidData object to a "shadow" of the full data model after a while, with empty objects, etc. It might be necessary to clean up/ignore such values before adding validation messages for everything in `dot.dot(invalidData)`?

**Review by olemartinorg — APPROVED** [review]
Fantastic!

**Comment by olemartinorg** [comment]
> Expression validations are now always run, meaning that there should not be any "field dependency" issues.

Does this mean that this also fixes #1847?

**Comment by bjosttveit** [comment]
> Does this mean that this also fixes #1847?

Well yeah, it is now a more naive implementation that runs much more often, so that should not be an issue now.

File: src/features/validation/invalidDataValidation/useInvalidDataValidation.ts (hunk 1 above)
Comment (olemartinorg) [reply src/features/validation/invalidDataValidation/useInvalidDataValidation.ts:19]: Yeah, I'm not 100% sure either. If you look at the result of `dot.dot(invalidData)` and it always only contains stringy values with invalid data (and not `null`, `{}`, etc), this isn't a problem after all. In older times we had the `flattenData()` function that did a `dot.dot()`, but also removed some values (such as empty objects), but it's worth noting that `dot.dot()` and that old `flattenData()` does not produce the same result (I've made that blunder a few times).

Comment (bjosttveit) [reply src/features/validation/invalidDataValidation/useInvalidDataValidation.ts:19]: Looks like empty objects will stay behind when removing nested properties, so I need some filtering I guess
