### PR TITLE
Fixing broken form data when going back via signing rejection

### LINKED ISSUE #3245: Å gå tilbake til første task: slette verdi i en repeterende gruppe fører til "Ukjent feil"
### Description of the bug

Våre skjemaer har to tasks: Utfylling og Signering. 

Dersom man legger inn data i en repeterende gruppe i Utfylling, går over til Signering, og deretter bestemmer seg for å gå tilbake til Utfylling for å så å slette en verdi i en repetrende gruppe, så kommer feilmeldingen "Ukjent feil" (An uncaught error occured). 

Eksempel på repeterende gruppe hvor man fører inn en verdi i første task (Utfylling hos oss):

Image

Feilmelding etter sletting:

Image

### Steps To Reproduce

1. Logg inn på: [https://brg.apps.tt02.altinn.no/brg/aarsregnskap-funk-202405/](https://brg.apps.tt02.altinn.no/brg/aarsregnskap-funk-202405/)
2. Fyll inn alle obligatoriske felter, inkludert f.eks. en e-postadresse på side to i hovedskjema. 
3. Gå over til signering/oppsummering (bytte task)
4. Gå tilbake til Utfylling, og deretter slett e-postadressen du la inn på side 2 i hovedskjema

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by olemartinorg**
## Description

As described in #3245, when rejecting and going back to the previous task, repeating group form data could be stale in a way that doesn't let you delete a row (that would cause a `409 conflict` as the data model on the backend had cleaned its `altinnRowId` fields). Invalidating the query cache when moving between process steps solves the issue.

## Related Issue(s)

- closes #3245

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [x] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [x] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [x] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [x] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` and `backport*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

File: src/features/formData/useFormDataQuery.tsx [hunk 1]
```diff
@@ -44,6 +45,10 @@ export function getFormDataQueryKey(url: string | undefined) {
   return ['fetchFormData', getFormDataCacheKeyUrl(url)];
 }
 
+export async function invalidateFormDataQueries(queryClient: QueryClient) {
+  await queryClient.invalidateQueries({ queryKey: ['fetchFormData'] });
+}
```
Comment (cammiida) [inline src/features/formData/useFormDataQuery.tsx:50]: Kan vi få inn en konstant for queryKeyen for formdata? Typ
```ts
  const formDataQueryKeys = {
    all: ['fetchFormData'] as const,
    detail: (url: string) => [...formDataQueryKeys.all, url] as const,
  };
```

**Review by cammiida — APPROVED** [review]
👌
