### PR TITLE
Fix/kan-ikke-velge-underenhet-2033

### LINKED ISSUE #2033: v4: Kan ikke velge underenhet
### Description of the bug

Hei, jeg har oppgradert skjema [elvirksomhet](https://altinn.studio/repos/dsb/elvirksomhet) til v8/v4. Skjemaet skal bare brukes av org-underenheter, eller overordnet enhet hvis ingen underenhet finnes. Konfig i `applicationmetadata.json`:
```
  "partyTypesAllowed": {
    "bankruptcyEstate": false,
    "organisation": true,
    "person": false,
    "subUnit": true
  },
```
Her er jeg logget inn som test-org-bruker 30874995556. Når jeg velger underenhet burde skjema initieres (ref [dok](https://docs.altinn.studio/community/changelog/app-frontend/v4/#most-users-will-be-prompted-for-party-each-time)) - men istedet bare kollapses valget.

https://github.com/Altinn/app-frontend-react/assets/5219898/3b23c7fb-df03-4202-9ae2-bfee776363e3

### Steps To Reproduce

1. Log in to tt02 as 30874995556
2. Go to https://dsb.apps.tt02.altinn.no/dsb/elvirksomhet
3. Try to select sub unit
4. Observe that it does not work - it is just collapsed

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by HauklandJ**
## Description

The issue was that `validParties` did not account for childParties.

Set valid parties based on the configuration in application metadata. 
The app metdata defines "partyTypesAllowed" - use this to filter out disallowed types.

## Related Issue(s)

- closes #2033

## Verification/QA
https://github.com/Altinn/app-frontend-react/assets/42615991/aabcc079-2e6e-4139-8faf-76edf495a117
- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
- Automated tests
  - [x] Unit test(s) have been added/updated
  - [ ] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [x] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [x] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [x] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

**Comment by HauklandJ** [comment]
nitpicks are appreciated!

File: src/features/party/partyProviderUtils.ts [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+      if (current.childParties) {
+        stack.push(...current.childParties);
+      }
+    }
+  }
+
+  return result;
+};
+
+export const GetValidParties = (parties: IParty[], appMetadata: IApplicationMetadata): IParty[] => {
```
Comment (olemartinorg) [inline src/features/party/partyProviderUtils.ts:21]: Since you wanted nitpicks - I think we usually reserve PascalCase for classes, and camelCase for functions (so since this is a function, i would have called it `getValidParties` or `reduceToValidParties`).

**Review by olemartinorg — APPROVED** [review]
Looks great! :partying_face: I appreciate the thorough tests!
