### PR TITLE
Wcag tab order is wrong when creating a new group

### LINKED ISSUE #908: WCAG: Tab order fix when creating a new group
### Description of the bug

When the user click the "legg til ny" button the next element in the tab order after pressing enter is the "rediger" button on the next repeating group component. It jumps over the entire group that you just said that you wanted to add. 

Picture One is before you click "legg til ny"
Skjermbilde 2023-02-08 kl  15 35 53

Picture 2 is after you pressed "Legg til ny" and tabbed once. The focus is on "rediger" button on the next component. It should be on the first input element of your newly made group. In this case: "1. Endre fra"
Skjermbilde 2023-02-08 kl  15 36 00

### Steps To Reproduce

1. Go to an app with repeating groups.
2. Try to create a new one using only your keyboard.
3. You should jump over the group you just created

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by lassopicasso**
## Description
Change tab order when a new group is added.

The repeating group container consists of a table with rows. Each row represents a group. When user adds a new group, it is added above the "add new group"-button. Hence the tab order doesn't visit the new group, but continues its path below.

To solve this issue, useRef and useEffect have been added. useEffect are rendered when a new group/row is created, and within this useRef locates it. When this has occurred, a logic checks if there are any focusable elements. If so, the focus() method is used to move the tab order to the first focusable element.

The code has also been refactored where the component “RepeatingGroupsEditContainer” has been split in two parts. The first one “RepeatingGroupsEditContainer” do some conditional checks before the “RepeatingGroupsEditContainerInternal” can be rendered. 

## Related Issue(s)

- closes #908 

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [x] Unit test(s) have been added/updated
  - [ ] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [x] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [ ] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [x] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Changes/additions to component properties
  - [ ] Changes are reflected in both `src/layout/layout.d.ts` and `layout.schema.v1.json`, and these are all backwards-compatible
  - [x] No changes made
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [x] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

File: src/features/form/containers/RepeatingGroupsEditContainer.tsx [hunk 1]
```diff
@@ -27,6 +38,38 @@ export interface IRepeatingGroupsEditContainer {
...
+      group={group}
+      row={row}
+      node={node}
+      language={language}
+      {...props}
+    />
+  );
+}
+
+export function RepeatingGroupsEditContainerInternal({
```
Comment (framitdavid) [inline src/features/form/containers/RepeatingGroupsEditContainer.tsx:72]: We should remove export on this method to ensure the functional component do not be used outside of this file.
```suggestion
function RepeatingGroupsEditContainerInternal({
```

File: src/features/form/containers/RepeatingGroupsEditContainer.tsx [hunk 2]
```diff
@@ -38,19 +81,59 @@ export function RepeatingGroupsEditContainer({
...
+
+      const isAvailable =
+        element.type !== 'hidden' || !element.disabled || (element.type.toLowerCase() === 'a' && !!element.href);
+
+      return focusableElements.includes(tagName) && isAvailable;
+    };
+
+    const findFirstFocusableElement = (container: HTMLElement): FocusableHTMLElement | undefined => {
+      return Array.from(container.getElementsByTagName('*')).find(isFocusable) as FocusableHTMLElement;
+    };
```
Comment (framitdavid) [inline src/features/form/containers/RepeatingGroupsEditContainer.tsx:125]: The linter want us to return the value immediately. :) 
```suggestion
    const findFirstFocusableElement = (container: HTMLElement): FocusableHTMLElement | undefined => Array.from(container.getElementsByTagName('*')).find(isFocusable) as FocusableHTMLElement;
```

File: src/features/form/containers/RepeatingGroupsEditContainer.tsx [hunk 3]
```diff
@@ -38,19 +81,59 @@ export function RepeatingGroupsEditContainer({
...
+
+    const firstFocusableChild = findFirstFocusableElement(gridRef.current);
+
+    if (firstFocusableChild) {
+      firstFocusableChild.focus();
+    }
+    /*
+     * Depend on group because renderLayoutNode method is invoked when group.rows[editIndex].items changes
+     * and generic components are rendered, hence we need to find the first focusable element once again.
```
Comment (framitdavid) [inline src/features/form/containers/RepeatingGroupsEditContainer.tsx:134]:
```suggestion
     * Depend on rowItems because generic components are rendered when rowItems change.
```

**Review by framitdavid — COMMENTED** [review]
Great work! 🚀

File: src/layout/FileUploadWithTag/FileUploadWithTagComponent.test.tsx [hunk 4]
```diff
@@ -160,12 +160,6 @@ describe('FileUploadWithTagComponent', () => {
         component: { maxNumberOfAttachments: 3 },
         attachments: getAttachments({ count: 2 }),
       });
-
```
Comment (framitdavid) [inline src/layout/FileUploadWithTag/FileUploadWithTagComponent.test.tsx:163]: I think we still need these tests. 😄

Comment (lassopicasso) [reply src/layout/FileUploadWithTag/FileUploadWithTagComponent.test.tsx:163]: Yeah I was wondering about that, but aren't they testing the same as the script below them (getByTestId and queryByTestId)?

File: src/features/form/containers/GroupContainer.tsx [hunk 5]
```diff
@@ -109,25 +110,29 @@ export function GroupContainer({ id }: IGroupProps): JSX.Element | null {
...
-    if (edit?.openByDefault && repeatingGroupIndex === -1) {
+  useEffect(() => {
+    if (!edit) {
+      return;
+    }
+    if (edit.openByDefault && repeatingGroupIndex === -1) {
       onClickAdd();
     }
-  }, [edit?.openByDefault, onClickAdd, repeatingGroupIndex]);
+  }, [edit, onClickAdd, repeatingGroupIndex]);
```
Comment (framitdavid) [inline src/features/form/containers/GroupContainer.tsx:120]: I think we should revert this back to what it was. Since now the dependency array depends on the whole edit object. But the implemented code only depends on `edit.openByDefault`.  Meaning that this `useEffect` runs even when something else than `openByDefault` changes.

File: src/features/form/containers/RepeatingGroupsEditContainer.tsx [hunk 6]
```diff
@@ -146,27 +244,9 @@ export function RepeatingGroupsEditContainer({
...
-              return null;
-            }
-            return (
-              <GenericComponent
-                key={n.item.id}
-                node={n}
-              />
-            );
-          })}
+          {getGenericComponentsToRender()}
```
Comment (framitdavid) [inline src/features/form/containers/RepeatingGroupsEditContainer.tsx:249]: I like this approach to avoid too much logic within the JSX. :)
