### PR TITLE
Prevent crash on save invalid decimal value

### LINKED ISSUE #1354: If you enter - on number fields the application crashes
### Description of the bug

Dersom vi skriver inn "-" på feltet "Sjøtemperatur" (gjelder alle felter som inneholder heltall) krasjer skjemaet. Men å skrive inn minus etter man først har skrevet inn et tall funker. Det gjelder dette skjema: [mat.apps.tt02.altinn.no/mat/lakselus-rapportering/](http://mat.apps.tt02.altinn.no/mat/lakselus-rapportering/)
Feltet er definert slik:
```
{
        "id": "lusetelling-sjoetemperatur",
        "type": "Input",
        "grid": {
          "sm": 4
        },
        "textResourceBindings": {
          "title": "Lakselusrapportering.lusetelling.sjoetemperatur",
          "help": "Lakselusrapportering.lusetelling.sjoetemperatur.hjelpetekst"
        },
        "dataModelBindings": {
          "simpleBinding": "lakselus.lusetelling.sjoetemperatur"
        },
        "required": true,
        "readOnly": false,
        "formatting": {
          "number": {
            "decimalScale": 1,
            "decimalSeparator": ","
          }
        }
      },



```

### Steps To Reproduce

Enter - on Sjøtemperatur field, os lusetelling fields. 

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by bjosttveit**
## Description

If the form data we save to the backend cannot be parsed into the strong types of the data model class, the save fails with 400 bad request and due to our handling of such errors, the app "crashes" with "unknown error". Since we use `decimal` as our preferred number type when generating the data model classes in studio (even if you select integer it seems), we should probably make sure that our `Input` component with number formatting is "safe" to use with numeric data types in the data model.

This change will check whether the number can be parsed into the `decimal` type before saving the data when using number formatting. The `react-number-format` already restricts what you can type into the box, but there are a few edge cases that this deals with. For example, you need to be able to type the characters `-` and `.` to support negative and floating point values; but these characters by themselves are not valid numbers and will cause a crash.

There is also a size restriction on `decimal` that will also cause a crash if not respected. So this also prevents a crash if you type a number that is too big. ~~A potential issue is that you do not get any feedback that the data you typed was not saved, this cannot easily be done with validation, since that requires the data to be saved first.~~

**EDIT**: I may have found a solution which is not too hacky. I am now forcing a rerender onBlur if the component has number formatting. Before, it would still show the entire number you typed even though it did not get saved, now you at least see the data you are actually going to submit.

https://github.com/Altinn/app-frontend-react/assets/47412359/a484e4e3-1898-4937-b159-a660edaae20e

## Related Issue(s)

- closes #1354 
- somewhat mitigates https://github.com/Altinn/app-lib-dotnet/issues/197 but only for `decimal` values which is default. It will still crash when used with `int`. 

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [x] Unit test(s) have been added/updated
  - [ ] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [x] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [x] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Changes/additions to component properties
  - [ ] Changes are reflected in both `src/layout/layout.d.ts` and `layout.schema.v1.json`, and these are all backwards-compatible
  - [x] No changes made
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [x] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

**Review by lassopicasso — APPROVED** [review]
Nice work on the fix(es)! Regarding the potential issue with fixing the crash caused by long decimal inputs and not receiving any feedback when the data is not saved, do I remember correctly that backend was either already working on or planning to address this in the future?

**Comment by bjosttveit** [comment]
> Nice work on the fix(es)! Regarding the potential issue with fixing the crash caused by long decimal inputs and not receiving any feedback when the data is not saved, do I remember correctly that backend was either already working on or planning to address this in the future?

I think it has been discussed. If so we could just remove this again.

File: src/hooks/useReload.ts [hunk 1]
```diff
@@ -0,0 +1,7 @@
+import { useCallback, useState } from 'react';
+
+export function useReload(key: string): [string, () => void] {
```
Comment (olemartinorg) [inline src/hooks/useReload.ts]: Huh, it's non-obvious to me what this is supposed to be used for.. Force-reloading a component? 🤔 Would love to see some doc comments with an example of use.

Comment (bjosttveit) [reply src/hooks/useReload.ts]: I added some comments, it looks like you reviewed not the latest commit
