### PR TITLE
Org num show for person

### LINKED ISSUE #1298: Party Selection/Personene vises med virksomhets ikon og orgnr
While investigating the bug below, we found some issues with party selection.

The task will also be implementing this diagram:

Image

### Description of the bug

Hvis jeg har bruker i Altinn som har org som default avgiver og prøver å starte en app som krever avgiver som fnr - så får jeg forventet feilmelding og nedenfor listes det tillatte brukere jeg kan velge ifra, men personene vises med foretaksikon og det står orgnr ved siden av

### Steps To Reproduce

1. Pålogget Altinn og rapporterer på vegne av organisasjon
2. Starter app som krever fnr for å kunne startes
3. Får feilmelding med oversikt over de personene jeg kan velge, men de står med virksomhetsikon og det står "orgnr" bak navnet

### Additional Information

image

### PR DESCRIPTION
**Pull request by adamhaeger**
## Description

Issue was present in v3 but not possible to reproduce in v4 as party selection did not work proprely.

Issue was fixed by fixing party selection.

Party selection is fixed according to this diagram:

partyselection

## Related Issue(s)

- closes #1298

After:

Screenshot 2024-04-05 at 17 38 29

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [x] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [x] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [ ] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [ ] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [x] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [ ] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

File: src/App.tsx [hunk 1]
```diff
@@ -2,45 +2,69 @@ import React from 'react';
...
+    return (
+      <Navigate
+        to={'/instance-selection/'}
+        replace={true}
+      />
+    );
+  }
+
+  return <InstantiateContainer />;
+};
```
Comment (olemartinorg) [inline src/App.tsx:26]: Hmm, I'm not quite sure why this was needed? It looks like this tries to do the same as Entrypoint does (but entrypoint supports way more, such as stateless apps (i.e. apps where the root path should load a form).

**Review by olemartinorg — COMMENTED** [review]
I'm sceptical. Make sure you add at least one cypress test to cover the fixes you did (i.e. a test that didn't pass before this change), and look over the failing tests here to make sure this change doesn't break existing functionality.

**Comment by olemartinorg** [comment]
I converted this to a draft for you - I was about to review it again since it's open, but I see there's still failing tests, complaints from CodeQL, etc.

File: src/features/applicationMetadata/index.d.ts [hunk 2]
```diff
@@ -29,7 +29,7 @@ export interface IOnEntry {
   instanceSelection?: IInstanceSelection;
 }
 
-export type ShowTypes = 'new-instance' | 'select-instance' | string;
+export type ShowTypes = 'new-instance' | 'select-instance' | 'stateless' | 'stateless-anon';
```
Comment (olemartinorg) [inline src/features/applicationMetadata/index.d.ts:32]: I don't think this quite correct. The show-type can be any string, not just 'stateless' (which then points to the layout set of the same name) and for some strange reason the setting for allowing anonymous users is defined on the _data type_ for that layout set. See the implementation of `useAllowAnonymous()`. So the previous type was correct, even though it reduces the possibilities to just 'string'.

File: src/features/entrypoint/Entrypoint.tsx [hunk 3]
```diff
@@ -39,39 +51,74 @@ export function Entrypoint() {
...
   }
 
-  if (show === 'select-instance') {
+  if (show === 'stateless') {
+    return <RenderStateless />;
+  }
+
+  if (show === 'stateless-anon') {
+    return <RenderStateless />;
+  }
```
Comment (olemartinorg) [inline src/features/entrypoint/Entrypoint.tsx:60]: These are configurable, and we should not hard-code them. The names can point to any layout-set, and this code will certainly break some applications (just not our test apps, since this here is now hard-coded to work for those).

File: src/features/instantiate/containers/PartySelection.tsx [hunk 4]
```diff
@@ -94,7 +94,7 @@ export const PartySelection = () => {
 
   const onSelectParty = async (party: IParty) => {
     await selectParty(party);
-    navigate('/'); // Back to Entrypoint.tsx, where the next step will be determined
+    navigate('/instance-selection');
```
Comment (olemartinorg) [inline src/features/instantiate/containers/PartySelection.tsx:97]: Instance selection is not always the path we want to go to after party selection. We should only show instance selection if that is configured (via `show === 'select-instance'`), so that's why we redirected back to the entrypoint earlier.

File: src/hooks/usePromptForParty.ts [hunk 5]
```diff
@@ -8,22 +8,24 @@ export function usePromptForParty(): boolean | null {
   const parties = useParties();
 
   if (!profile?.partyId || !parties) {
+    console.log('null');
```
Comment (olemartinorg) [inline src/hooks/usePromptForParty.ts:11]: Remove the calls to `console.log` (we have automatic checks for this as well, as you can see in the files tab).

File: test/e2e/integration/frontend-test/party-selection.ts [hunk 6]
```diff
@@ -40,27 +151,77 @@ describe('Party selection', () => {
...
+        person: true,
+        subUnit: false,
+        bankruptcyEstate: false,
+        organisation: false,
+      },
+    });
+
+    cy.startAppInstance(appFrontend.apps.frontendTest);
+
+    // TODO: Implement the rest
```
Comment (olemartinorg) [inline test/e2e/integration/frontend-test/party-selection.ts:167]: I guess this test can be deleted if not implemented, though, I see that it would have been failing if implemented (as mentioned from what I saw in the Percy screenshot).

**Review by olemartinorg — CHANGES_REQUESTED** [review]
I believe this change would break some apps, as this now hard-codes all `applicationMetadata.onEntry.show` values to be one of a fixed list of options. That works for our test apps, but apps out there in the wild uses other names for their layout sets than we do.

There's also the issue that we always redirect to instance selection after party selection now, which probably also works for our test-cases, but it should be up to the app developers (and again, what they set in `onEntry.show`) to decide what we should do next after party selection. For stateless apps, for example, it doesn't make sense for us to fetch a list of instances or force the user to create a new one.

**Review by olemartinorg — APPROVED** [review]
Great work! :raised_hands:

**Comment by elenagustafsson** [comment]
Jeg får fortsatt personene med ordet orgnr og ikonen for orgnr både i prod og i TT2, når kommer rettelsen til miljøene?
image

**Comment by olemartinorg** [comment]
@elenagustafsson Endringer kommer først på plass når vi lanserer en ny versjon av app-frontend (altså ikke når vi merger inn en pull request). Regner med vi kan lansere en ny versjon tidlig neste uke. Vi pleier vanligvis å vente med å lansere til starten av en uke, slik at vi har best mulig anledning til å oppdage eventuelle følgefeil i løpet av en arbeidsuke. :blush:

**Comment by elenagustafsson** [comment]
Det er fortsatt samme feil både i TT2 og prod, blir dette rettet? 
image

**Comment by olemartinorg** [comment]
@elenagustafsson Dette skal ha blitt rettet i versjon 4.2.2, ja. Jeg sjekket med en tilfeldig app nå, og det ser riktig ut der - hvilken app er skjembildet av?

**Comment by elenagustafsson** [comment]
Dette er RF-1551. Likt i prod og TT2. Og skjema skal bare kunne brukes av orgnr, trodde ikke at fnr skulle vises i det hele tatt.

**Comment by olemartinorg** [comment]
Aha, jeg ser den appen bruker versjon 3 av app-frontend fortsatt. Vi har fikset dette i versjon 4 (spesifikt 4.2.2, som nevnt), og vi fikser bare mer kritiske feil i versjon 3 (typisk feil som hindrer utfylling eller innsending). Les mer om oppgradering til v4 i [migrasjonsguiden](https://docs.altinn.studio/community/changelog/app-frontend/v4/migrating-from-v3/) og dokumentasjonen som beskriver [endringer fra v3](https://docs.altinn.studio/community/changelog/app-frontend/v4/).
