### PR TITLE
Fix DevTools in subform

### LINKED ISSUE #2818: DevTools does not work in subform
### Description of the bug

If you open devtools inside of a subform, or navigate to a subform while dev tools is open the page crashes with the following message:

Image

### Steps To Reproduce

.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by bjosttveit**
## Description

Fixes dev-tools crashing in subform. Also makes the subform-loading look a bit better by not showing an empty form container.

Added an error boundary inside of the dev tools panel as well, so errors like this are less annoying in the future

Cleaned up dev tools component by removing `{children}` since we no longer wrap the application in it.

## Related Issue(s)

- closes #2818 

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [ ] Cypress E2E test(s) have been added/updated
  - [x] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [x] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [x] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [x] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

**Review by olemartinorg — APPROVED** [review]
Looks great! :raised_hands:

File: src/core/loading/Loader.tsx [hunk 1]
```diff
@@ -14,17 +13,8 @@ interface LoaderProps {
 }
 
 export const Loader = (props: LoaderProps) => {
-  const overriddenDataModelUuid = useTaskStore((state) => state.overriddenDataModelUuid);
-  const overriddenTaskId = useTaskStore((state) => state.overriddenTaskId);
   const hasPresentation = useHasPresentation();
 
-  if (overriddenDataModelUuid) {
```
Comment (danielskovli) [inline src/core/loading/Loader.tsx:21]: All of these task-store checks in the loader was something we added to avoid the "page is loading" for each subform during the PDF render.

Have you tested how this now looks during PDF generation?

Comment (olemartinorg) [reply src/core/loading/Loader.tsx:21]: Good point. Also counts for summaries of subforms.

Comment (bjosttveit) [reply src/core/loading/Loader.tsx:21]: Nope, will check

Comment (bjosttveit) [reply src/core/loading/Loader.tsx:21]: What do you think of this? As a compromise. Still showing the loader, but not the Presentation around it. 

Summary:
image

PDF:
image

Comment (bjosttveit) [reply src/core/loading/Loader.tsx:21]: Ready for print waits for subform data to be loaded. There should not be any difference really other than visual. It just shows a loader instead of nothing until the data is ready

Comment (bjosttveit) [reply src/core/loading/Loader.tsx:21]: Unless i am missing something @danielskovli

Comment (danielskovli) [reply src/core/loading/Loader.tsx:21]: @bjosttveit @olemartinorg   Last time I was involved in this part of the code, the ready-for-print mechanism waited for all subform data to finish loading 👌 

The Loader modifications were only visual if I remember correctly. Worth noting that the `overriddenTaskId` check was already in there, I think perhaps @adamhaeger had added it as part of the Summary2 feature.

Comment (adamhaeger) [reply src/core/loading/Loader.tsx:21]: `overriddenTaskId` is (or was?) needed to render summary of a previous task.

But there should be a cypress test for this and they all seem to be passing so IDK 😆

Comment (adamhaeger) [reply src/core/loading/Loader.tsx:21]: I like the new skeleton loader 👍

Comment (bjosttveit) [reply src/core/loading/Loader.tsx:21]: Still is, this will just show a loader instead of null while it loads. Due to `useHasPresentation` it should just show the loader and not the `Presentation` container around it. In PDF however we don't have any `Presentation` container, so I added a `DummyPresentation` that only sets the provider so that loading will not create its own `Presentation` there either
