### PR TITLE
Fixing support for markdown in multiple labels

### LINKED ISSUE #2362: Broken HTML-support for radiobutton title in frontend version 4.6
### Description of the bug

When making a list with HTML-tags ul and li, it did not look like a list when I used it as a title for a radiobutton. When I used the exact same text as a title for an Input-field, it looked as I expected. Here is what it looked like in version 4.6: 
image

In version 4.5.0 it looked like this (it's still not exactly what I would expect, since only the list elements are bold): 
image

### Steps To Reproduce

Use f.ex. this text id:
 ` {
      "id": "S09_TapGevinstNedskrivinger.RadioButtons-nedskrivinger-hjycaU.title",
      "value": "Hadde foretaket noe av det følgende overfor utlandet per {0}?<ul><li>Salgs- eller markedsgevinster på eiendeler eller gjeld</li><li>Salgs- eller markedsverditap på eiendeler eller gjeld</li><li>Avskrivinger</li><li>Nedskrivinger</li><li>Gjeldsettergivelse</li><li>Forhøyelse av aksjekapitalen</li><li>Nedsettelse av aksjekapitalen</li></ul>",
      "variables": [
        {
          "key": "SkjemaData.Prefill.datoHittilAar",
          "dataSource": "dataModel.A3_RA-0532_M"
        }
      ]
    },`

as a "title" for a RadioButton-component.

### Additional Information

Mentioned on Slack https://altinn.slack.com/archives/C02EJ9HKQA3/p1724840292390499

### PR DESCRIPTION
**Pull request by olemartinorg**
## Description

Multiple labels seemed to have broken support for markdown. This worked in `v4.5.0`, so it was an unintended breaking change when rewriting the labels functionality. Opening PR now to see how much Percy will find, and I'll focus on adding better tests for this later (after some meetings). 

## Related Issue(s)

- closes #2362

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [x] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [x] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [x] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [x] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

File: src/layout/RadioButtons/ControlledRadioGroup.tsx [hunk 1]
```diff
@@ -35,16 +34,18 @@ export const ControlledRadioGroup = (props: IControlledRadioGroupProps) => {
...
   const labelText = (
     <LabelContent
       componentId={id}
-      label={[getLabelPrefixForLikert(), langAsString(textResourceBindings?.title)].join(' ')}
+      label={
+        <>
+          {leftColumnHeader ? `${langAsString(leftColumnHeader)} ` : null}
+          <Lang id={textResourceBindings?.title} />
+        </>
+      }
```
Comment (bjosttveit) [inline src/layout/RadioButtons/ControlledRadioGroup.tsx:48]: Is there a reason for using `langAsString` on `leftColumnHeader` instead of `<Lang />`?

**Review by bjosttveit — APPROVED** [review]
Nice!
