### PR TITLE
ExternalApi on SimpleTable does not support path parameter

### LINKED ISSUE #3131: SimpleTable with ExternalAPI shows only first element.
### Description of the bug

SimpleTable with ExternalAPI shows only first element.  Seems like maybe the path does not work.

### Steps To Reproduce

1. Set up a simpletable component
2. ExternalApi attributes

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by paal2707**
## Description

Make use of path property to filter to the correct data on externalApi on SimpleTable

## Related Issue(s)

- closes #3131 

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [ ] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [x] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [ ] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [ ] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

File: src/layout/SimpleTable/ApiTable.tsx [hunk 1]
```diff
@@ -31,8 +31,14 @@ export function ApiTable({ node, externalApi }: ApiTableProps) {
...
 
+  const dataForPath = pick(externalApi.path, data[externalApi.id]);
+
+  if (!dataForPath) {
+    return null;
+  }
+
   let dataToDisplay: FormDataObject[] = [];
-  const value = data[externalApi.id];
+  const value = dataForPath;
```
Comment (bjosttveit) [inline src/layout/SimpleTable/ApiTable.tsx:41]: Nitpick, but couldn't `dataForPath` just be called `value`, instead of declaring and assigning it to `value` afterwards?

**Review by bjosttveit — APPROVED** [review]
Looks good!
