### PR TITLE
Don't show unknown error if the user can retry submit

### LINKED ISSUE #2107: Handle PDF failure error instead of showing unknown error
### Description

Now that apps will unlock data elements when PDF fails, we should improve the experience for the end user when PDF fails. We should handle the error from the backend and inform the user that something went wrong and that they can try submitting again. Instead of showing the "Unknown error"-page.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by bjosttveit**
## Description

Since version [8.1.0](https://github.com/Altinn/app-lib-dotnet/releases/tag/v8.1.0) of app-lib-dotnet the app will unlock the data elements if PDF fails [#523](https://github.com/Altinn/app-lib-dotnet/pull/523). For apps with this version or later we don't need to show unknown error if process/next fails due to PDF, but rather ask them to try again.

## Related Issue(s)

- closes #2107

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [ ] Cypress E2E test(s) have been added/updated
  - [x] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [x] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [x] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [x] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

File: src/features/instance/ProcessNavigationContext.tsx [hunk 1]
```diff
@@ -104,6 +116,10 @@ function useProcessNext() {
   return { perform, error: utils.error };
 }
 
+function appUnlocksOnPDFFailure({ altinnNugetVersion }: ApplicationMetadata) {
+  return !altinnNugetVersion || isAtLeastVersion({ actualVersion: altinnNugetVersion, minimumVersion: '8.1.0.115' });
```
Comment (cammiida) [inline src/features/instance/ProcessNavigationContext.tsx:120]: Bare dobbeltsjekker at logikken er riktig: Enten at `altinnNugetVersion` ikke er satt, eller at den er minst versjon `8.1.0.115`?

**Review by cammiida — APPROVED** [review]
LGTM! 👌

File: src/features/instance/ProcessNavigationContext.tsx (hunk 1 above)
Comment (bjosttveit) [reply src/features/instance/ProcessNavigationContext.tsx:120]: Heh, tenkte jeg ikke på en gang, jeg bare kopierte blindt fra et annet sted 😅 

Jeg tror eneste grunnen for at jeg la det inn er at den er nullable, men det har ingenting å si fordi hvis den ikke er definert, så funker ikke appen i det hele tatt og vi viser error-page. Det betyr basically at nuget-versjonene er lavere enn v8 som vi ikke støtter.

```ts
isValidVersion:
  !!data.altinnNugetVersion &&
  isAtLeastVersion({
    actualVersion: data.altinnNugetVersion,
    minimumVersion: MINIMUM_APPLICATION_VERSION.build,
}),

```
