### PR TITLE
Summary edit button accessibility 

### LINKED ISSUE #909: WCAG: Focus visible has disappeared from the edit buttons on the summary component
### Description of the bug

If you try to navigate a summary page using only a keyboard you will not be able to see what "endre" button has focus.
In this screenshot the focus is on one of the "endre" buttons
Skjermbilde 2023-02-08 kl  15 40 14

Focus should be the same as for our other component. 

### Steps To Reproduce

Go to an app with a summary page
Try to navigate it with only a keyboard
All "endre" buttons should not have any focus

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by lassopicasso**
## Description

Replaced the button with the button from the design system.

## Related Issue(s)

- closes #909 

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [ ] Cypress E2E test(s) have been added/updated
  - [x] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [x] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [ ] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [x] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Changes/additions to component properties
  - [ ] Changes are reflected in both `src/layout/layout.d.ts` and `layout.schema.v1.json`, and these are all backwards-compatible
  - [x] No changes made
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [x] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

File: src/components/summary/EditButton.tsx [hunk 1]
```diff
@@ -1,45 +1,22 @@
...
-      >
-        <span>{props.editText}</span>
-        <i
-          aria-hidden='true'
-          className={`fa fa-editing-file ${classes.editIcon}`}
-        />
-      </Typography>
-    </IconButton>
+      {props.editText}
+    </Button>
```
Comment (bjosttveit) [inline src/components/summary/EditButton.tsx:20]: I think you forgot to add the `onClick` event 😅

**Review by bjosttveit — CHANGES_REQUESTED** [review]
Make sure to also check that clicking the button works, as well as the tabbing 😄

**Review by bjosttveit — APPROVED** [review]
Very nice!

**Comment by bjosttveit** [comment]
@lassopicasso Looks like the cypress test for summary needs to be updated. Since the button has changed, it is no longer able to find it, because it looks for a `Material-Ui` button.
