### PR TITLE
fix: fixed navigation to the relevant input field

### LINKED ISSUE #3967: Navigasjon via feilmedlingslink feiler for inputfelt med markdown-lister
### Description of the bug

Appen klarer ikke å navigere til inputfelt via feilmedlingslinken når feltets beskrivelse inneholder Markdown-lister med tekst foran listen. Dersom beskrivelsen kun består av en liste, fungerer navigasjonen som forventet. Problemet oppstår altså når det er innledende tekst før Markdown-listen; fjerning av denne gjør at navigasjonen fungerer korrekt.
Man får også dette i URl da en klikker på feilenlenken : S05_Innleie?focusComponentId=S05-Innleid-Input-MpYwxu&focusErrorBinding=simpleBinding

Image

### Steps To Reproduce

https://altinn.studio/repos/ssb/ra0479-02 commit 3622185e9b635ffbe472fc62527be6273cb92657
Dette kan testes på side 5. Tekstressursen Side05_innleie.Input-MpYwxu.description inneholder beskrivelsen. Feltet er påkrevd og vil gi valideringsfeil dersom det ikke fylles ut. Når man klikker på feillenken, navigerer ikke appen til det aktuelle inputfeltet.

Slack: https://digdir-samarbeid.slack.com/archives/C02EJ9HKQA3/p1769156460722419

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by JamalAlabdullah**
## Related Issue(s)

- closes #3967 

https://github.com/user-attachments/assets/f7e19d6b-b504-460a-9242-e2bfe4db3073

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [ ] Cypress E2E test(s) have been added/updated
  - [x] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [x] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [ ] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [x] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [x] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [ ] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` and `backport*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out
  

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved keyboard focus behavior: broader detection of focusable elements (buttons, tabindex, contenteditable), returns no focus for empty containers, honors an optional binding preference, and applies a clear fallback order (preferred binding → first input-like → first available).
* **Tests**
  * Added comprehensive tests covering focus selection scenarios and fallback paths.

### CODE REVIEW

File: src/layout/GenericComponent.tsx [hunk 1]
```diff
@@ -267,19 +267,44 @@ function cleanupQuery(searchParams: URLSearchParams, setSearchParams: SetURLSear
...
+      ),
+    ),
+  );
+
+  if (targetElements.length === 0) {
+    return undefined;
+  }
+
+  const hasBinding = binding !== null;
+  const matchesBinding = (element: HTMLElement) => hasBinding && element.dataset.bindingkey === binding;
```
Comment (walldenfilippa) [inline src/layout/GenericComponent.tsx]: Minor nitpick: `matchesBinding` is only called inside an if statement that already checks if hasBinding == true, so the additional `hasBinding` check on line 288 is unnecessary.

**Review by walldenfilippa — APPROVED** [review]
Nice job! I left a minor nitpick :)

File: src/layout/GenericComponent.tsx (hunk 1 above)
Comment (JamalAlabdullah) [reply src/layout/GenericComponent.tsx]: Fixed
