### PR TITLE
Likert: Remove extra labelledById attribute

### LINKED ISSUE #1535: Radiobutton label is read  4 times in Likert
### Description of the bug

When using NVDA screen reader the radio likert is read 4 times. 

### Steps To Reproduce

1. Go to likert, use nvda and klikk a radiobutton
2. The screen reader reads out the label 4 times

### Additional Information

Additionally the name attribute is not present in Likert table view. This breaks using arrows to change the radio values.

### PR DESCRIPTION
**Pull request by lasseklovstad**
…added.

## Related Issue(s)

- closes #1535

## Verification/QA

- Manual functionality testing
  - [ ] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [ ] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [ ] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [ ] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [ ] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [ ] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [ ] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

File: src/components/form/RadioButton.tsx [hunk 1]
```diff
@@ -21,6 +21,14 @@ export const RadioButton = ({ showAsCard = false, label, helpText, hideLabel, ..
       {helpText ? <HelpText title={getPlainTextFromNode(helpText)}>{helpText}</HelpText> : null}
     </div>
   );
+
+  useEffect(() => {
+    // Name attribute is not added by digdir design system
+    if (inputRef.current && rest.name) {
+      inputRef.current.name = rest.name;
+    }
+  }, [rest.name]);
```
Comment (olemartinorg) [inline src/components/form/RadioButton.tsx:30]: Instead of working around shortcomings in the design system in our own code, we should probably [improve this in the design system](https://github.com/digdir/designsystem). Having this code here requires us to maintain it, it does not benefit anyone else using the design system, and would overwrite (and possibly break things) in the future if the design system adds the name on their own.

Comment (lasseklovstad) [reply src/components/form/RadioButton.tsx:30]: Okei should i create an issue? Can we contribute to their repository or do we wait until they fix it?

Comment (olemartinorg) [reply src/components/form/RadioButton.tsx:30]: You can create a PR there just as you can to this repo - it's all open source. 🙌

Comment (lasseklovstad) [reply src/components/form/RadioButton.tsx:30]: Created a PR here: https://github.com/digdir/designsystem/pull/903

**Review by olemartinorg — APPROVED** [review]
Code looks good! There are a couple of cypress test failing, but at least one of them are known problems right now in main.

PS: As you might have heard, we're working on v4 right now, so the `main` branch tracks that progress. I'm assuming you'd want this fix cherry-picked into the `v3` branch, along with upgrading the design system dependency there. Before we can do that, we have to take care of #1520, so it might take some time. Please let me know how high of a priority this is for you to release in v3, and if we have any deadlines. 🙏

**Comment by lasseklovstad** [comment]
> Code looks good! There are a couple of cypress test failing, but at least one of them are known problems right now in main.
> 
> PS: As you might have heard, we're working on v4 right now, so the `main` branch tracks that progress. I'm assuming you'd want this fix cherry-picked into the `v3` branch, along with upgrading the design system dependency there. Before we can do that, we have to take care of #1520, so it might take some time. Please let me know how high of a priority this is for you to release in v3, and if we have any deadlines. 🙏

Hey, we would love to have it in version 3 if possible. It is not a very serious bug, we have marked it as a C-bug (where A is a blocker). Our users will start using the application from 6.11.2023 so if this gets released at least one week before that it would be of help to us.

If it is not fixed we will just add it to the list of Wcag violations and screen reader users will have to listen to the question be read two times.

**Comment by lasseklovstad** [comment]
@olemartinorg Hey again. We decided during standup to not wait for this fix and lock our frontend version to the current version. So you don't have to stress to fix this.

**Comment by olemartinorg** [comment]
@lasseklovstad I tested this in `v3.68.2` now, using Wave. I now get the 'empty form label' error once for every radio in the Likert, but I don't get any when testing with `v3.68.1` before this fix? 🤔 Do you get the same results, or might there be something with our `ttd/frontend-test` app that's different from the apps you're testing?

Anyway, when using the NVDA screen reader I get the same results (as far as I can hear) between `v3.68.2` and `v3.68.1` when testing by tabbing through radio buttons. NVDA reads both the question and the answer alternative twice for me on both versions.

**Comment by lasseklovstad** [comment]
> @lasseklovstad I tested this in `v3.68.2` now, using Wave. I now get the 'empty form label' error once for every radio in the Likert, but I don't get any when testing with `v3.68.1` before this fix? 🤔 Do you get the same results, or might there be something with our `ttd/frontend-test` app that's different from the apps you're testing?
> 
> Anyway, when using the NVDA screen reader I get the same results (as far as I can hear) between `v3.68.2` and `v3.68.1` when testing by tabbing through radio buttons. NVDA reads both the question and the answer alternative twice for me on both versions.

Yes i see the issue with waves and empty label now. Eventhough label is undefined RadioButton Renders an empty label which is passed down to altinn radio component. Resulting in empty label. 

With version 3.68.1 using NVDA with arrows to navigate through likert it reads the following when encountering the row:
question -> answer 1 -> question and answere 1 ->  answer 2 -> question and answere 2 ...

With the new version it doesn't read the label because it is blank and it reads a row like this:
question -> answer 1 ->  answer 2  ...

When testing it is important to notice that i am not using tab but the arrow keys (up and down). When using tab you jump straight into the table and the screen ready will read up header and row you are currently in before reading the content of the cell your inn. Screen reader users are more likly to use the arrow keys because then they read all the information one by one instead of jumpoing over non focusable items.
