### PR TITLE
fix: we can now render previous task summaries in pdf

### LINKED ISSUE #2191: Make new summary rendring work with pdf work when rendring previous tasks

### PR DESCRIPTION
**Pull request by adamhaeger**
## Description

Now rendering SummaryComponent2 in the PDF component so that previous tasks are resolved correctly.

## Related Issue(s)

- closes #2191 

## Verification/QA

- Manual functionality testing
  - [ ] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [ ] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [ ] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [ ] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [ ] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [ ] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [ ] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

**Review by olemartinorg — APPROVED** [review]

File: src/features/pdf/PdfView2.tsx [hunk 1]
```diff
@@ -84,6 +86,15 @@ export const PDFView2 = () => {
...
             .map((node) => {
+              if (node.item.type === 'Summary2' && node.item.target?.taskId) {
+                return (
+                  <SummaryComponent2
+                    key={node.item.id}
+                    summaryNode={node as BaseLayoutNode<CompSummary2Internal, 'Summary2'>}
+                  />
+                );
+              }
+
```
Comment (olemartinorg) [inline src/features/pdf/PdfView2.tsx:97]: Btw, doesn't this mean that all other Summary2 components in a layout will fall through and render with ComponentSummary? Maybe that doesn't matter as `renderSummary2()` returns `null`. However, the comment over there (_"If the code ever ends up with a [...]"_) indicates that it shouldn't happen, but now it definitely will happen.
