### PR TITLE
Do not stop the user on warning when submiting the form

### LINKED ISSUE #167: Man må klikke 2 ganger på send inn ved bruk av myke kontroller i skjema
## Description
Man må trykke på send inn knappene i skjemaet 2 ganger, når man har myke kontroller i skjema. 

## To Reproduce
Repo som bugen dukket opp i https://altinn.studio/repos/stian.vestli/ra0000-kontaktogkommentar.git
Enkelt skjema med bare 4 felter og en avhuking.
image

Avhukning har en hard kontroll, denne trigger også validering som setter Myke kontroller i ValidateData eventet.
`if (string.IsNullOrEmpty(model.Kontakt.kontaktPersonNavn))
               {
                    validationResults.AddModelError("Kontakt.kontaktPersonNavn", "*WARNING*SkjemaNavn.Error"); // viser feilen på feltet MYK kontroll
                }`

Denne kontrollen er satt på alle 3 felter foruten kommentarfeltet.
Den harde kontrollen er også tatt hånd om i ValidateData:
`if (string.IsNullOrEmpty(model.Kontakt.kontaktInfoBekreftet))
                {

                    validationResults.AddModelError("Kontakt.kontaktInfoBekreftet", "SkjemaBekreftelse.Error"); 
                    validationResults.AddModelError(nameof(Kontakt.kontaktInfoBekreftet), "SkjemaBekreftelse.Error"); øverst i bildet
                    
                }else
                {
                     validationResults.AddModelError(nameof(Kontakt.kontaktInfoBekreftet), "*FIXED*SkjemaBekreftelse.Error"); //*FIXED* 
                }`

For den harde settes det 2 feilmedlinger for å vise hvilket felt det feiler på på toppen av skjema ved kontroll, det settes også en FIXED tag slik at denne fjernes når feilen er rettet.

Ved å trykke send inn uten å ha fylt ut noe vil den stoppe deg:
image

Hvis man nå huker av bekreft så skal man kunne sende inn skjema siden resten av kontrollene er myke:
image

Her må man da trykke 2 ganger på send inn, første gangen tenker den bare litt også skjer det ikke noe mer.

## Expected behavior
Et trykk på send inn skal være nok siden det er myke kontroller.

### PR DESCRIPTION
**Pull request by framitdavid**
## Description
The user should be able to submit the form by clicking submit once as long there are no errors. Before we stopped the user if there were some warnings (soft validations). I have removed "ignoreWarnings: false" when submitting a form, and that was the fix due to the issue. 

All the unit tests that have been changed are because of the clean-up within the `updateFormData` method.

## Related Issue(s)

- closes #167

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [x] Unit test(s) have been added/updated
  - [ ] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [x] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [x] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Changes/additions to component properties
  - [ ] Changes are reflected in both `src/layout/layout.d.ts` and `layout.schema.v1.json`, and these are all backwards-compatible
  - [x] No changes made
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [ ] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [ ] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

File: src/components/hooks/useDelayedSavedState.ts [hunk 1]
```diff
@@ -14,31 +14,32 @@ export function useDelayedSavedState(
...
-      if (value !== formValue) {
-        validate && handleDataChange(value);
-        !validate && handleDataChange(value, { validate: false });
-        if (skipNextValidation) {
-          setSkipNextValidation(false);
-        }
-        if (saveNextChangeImmediately) {
-          setSaveNextChangeImmediately(false);
-        }
+  const updateFormData = useCallback(
```
Comment (framitdavid) [inline src/components/hooks/useDelayedSavedState.ts:30]: This was just a small refac to make the code more readable.

**Review by Magnusrm — APPROVED** [review]
Nice work! 🔧 Looks good to me
