### PR TITLE
WCAG/Change structure of summary content

### LINKED ISSUE #1029: WCAG fixes on the summary component
## Reading order
Today the reading order on the summary component is Label - "endre" button - Value. When using a screen reader this might be a little confusing. We should change it so that the button is the last element on summary element. 
**Example:** 
1. Is how it is today
2. How it should be
Frame 1
The screen reader use the order of the code, if we change it we would have hack it to behave how we want it to. Maybe the easiest solution is to change the design so that the button is visually also the last element. 
Skjermbilde 2023-03-22 kl  15 05 25

- [ ] Change the design so that the "endre" button is last in the reading order

## The button is not descriptive enough
Moved to a separate issue:  #1100

### Steps To Reproduce

Go to an app with a summary page and use a screen reader when testing

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by lassopicasso**
## Description
Changed the HTML-structure of summary content to make it more WCAG-friendly:
Before: `Label -> Edit Btn -> Summary`
After: `Label -> Summary -> Edit Btn`
Used grid-template-areas to make the structure look visually the same as before.

>Needed to update cypress, due to more layers made with the solution I came up with.
>Instead of adding more layers to these paths in cypress, I removed them and kept just one selector. If this isn't a proper way to do it, or/and could risk any harm later on, I will change it back and add extra layer instead :) 

## Related Issue(s)

- closes #1029 

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [x] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [x] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [ ] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [x] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Changes/additions to component properties
  - [ ] Changes are reflected in both `src/layout/layout.d.ts` and `layout.schema.v1.json`, and these are all backwards-compatible
  - [x] No changes made
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [x] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

File: src/layout/Summary/SummaryContent.tsx [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+import type { ISummaryComponent } from 'src/layout/Summary/SummaryComponent';
+import type { LayoutNodeFromType } from 'src/utils/layout/hierarchy.types';
+import type { LayoutNode } from 'src/utils/layout/LayoutNode';
+
+export interface SummaryContentProps {
+  onChangeClick: () => void;
+  changeText: string | null;
+  label: React.ReactNode;
+  summaryNode: LayoutNodeFromType<'Summary'>;
+  targetNode: LayoutNode | any;
```
Comment (olemartinorg) [inline src/layout/Summary/SummaryContent.tsx:17]: Do we need `| any` here? That just removes typescript support for that property..

Comment (olemartinorg) [reply src/layout/Summary/SummaryContent.tsx:17]: I guess it's because the check for `'renderSummaryBoilerplate' in component` is not narrowing the LayoutNode down to just summary-renderable-components anymore. I think it's best to keep the code strict and check that either inside this React component or outside it (and pass in the narrowed type).

Comment (lassopicasso) [reply src/layout/Summary/SummaryContent.tsx:17]: Good point, thanks Ole Martin :)
