### PR TITLE
WCAG: Likert component fixes

### LINKED ISSUE #316: WCAG issues with the likert component
### Description of the bug

There are a couple of WCAG issues with the "likert component" that should be fixed. 

## 1. Title element is a h5. 
We should avoid headers in our components, and if we need them they should probably be h2 by default and possible to edit by the app developer. As it is now it will in most cases cause the app to fail the [1.3.1. info and relationships](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships) by jumping over some elements in the header order.
[Example of how header structure should be (Norwegian)](https://www.uutilsynet.no/veiledning/tekst-og-struktur/226#overskriftsniver)

Skjermbilde 2022-07-04 kl  15 36 10

## 2. Empty `<th>` element
There is an empty header element in the table. This is breaking [1.3.1. info and relationships](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships)
Skjermbilde 2022-07-04 kl  15 37 42

## 3. Empty labels
The testing tool Wave is giving a warning that the component contain labels, but that they do noy have any content. I tested it with a screen reader and every bit of information in relation to the radio button was read. (Tested with VoiceOver) Maybe look into if the labels should be structured in another way? 

One weird bug was that the label was read twice by Voice Over
Skjermbilde 2022-07-04 kl  15 25 19

### Steps To Reproduce

Go to an app with a likert component
Run wave or another testing tool

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by mijohansen**
## Description

This is a pr to help the apps-team. Extensive PR-comments could be added by receiving team if needed. 

## Related Issue(s)

- closes #316

## Verification

- Manual testing
  - [ ] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added
  - [ ] Cypress E2E test(s) have been added
  - [ ] No automatic tests are needed here
  - [ ] I want someone to help me make some tests
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been updated
  
  - [ ] No changes/updates needed
- Changes/additions to component properties
  - [ ] Changes are reflected in both `src/layout/layout.d.ts` and `layout.schema.v1.json`, and these are all backwards-compatible
  - [ ] No changes made
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [ ] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [ ] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board

### CODE REVIEW

File: src/features/form/containers/GroupContainer.tsx [hunk 1]
```diff
@@ -189,6 +191,8 @@ export function GroupContainer({ id, container, components }: IGroupProps): JSX.
     return null;
   }
 
+  const isNested = typeof container.baseComponentId === 'string';
```
Comment (Magnusrm) [inline src/features/form/containers/GroupContainer.tsx:194]: Adding type for strict typechecking.
```suggestion
  const isNested: boolean = typeof container.baseComponentId === 'string';
```

File: src/features/form/containers/GroupContainer.tsx [hunk 2]
```diff
@@ -233,58 +237,65 @@ export function GroupContainer({ id, container, components }: IGroupProps): JSX.
...
-                setEditIndex={setEditIndex}
-                onClickRemove={onClickRemove}
-                repeatingGroupDeepCopyComponents={repeatingGroupDeepCopyComponents}
-                forceHideSaveButton={true}
-              />
-            );
-          })}
+                return (
+                  <div
+                    key={index}
```
Comment (Magnusrm) [inline src/features/form/containers/GroupContainer.tsx:277]: I see you did not change this, but i think the id is safer to use as key here than the index.
```suggestion
                    key={`key-${id}`}
```

**Review by Magnusrm — APPROVED** [review]
Nice work! Thanks for the contribution 🙏  Some minor nitpicking below.

File: src/features/form/containers/GroupContainer.tsx (hunk 1 above)
Comment (olemartinorg) [reply src/features/form/containers/GroupContainer.tsx:194]: Personally, I'm not a fan of "strict" typechecking. TypeScript is best when it's not in your way, and TypeScript is smart enough to figure out that the return value from a comparison is a boolean. There's no need to write anything more than we absolutely _have_ to. In the future I want to enable `noImplicitAny` in `tsconfig.json` so that we are nagged to specify types wherever TypeScript _can't_ automatically infer the type.

Comment (Magnusrm) [reply src/features/form/containers/GroupContainer.tsx:194]: I must have misunderstood some previous talk about typechecking then 😅 Thanks for clarifying! I have no problem personally with keeping the types inferred where they can be 👍

Comment (mijohansen) [reply src/features/form/containers/GroupContainer.tsx:194]: This is not code that this PR touches, so this is out of scope.

File: src/features/form/containers/GroupContainer.tsx (hunk 2 above)
Comment (mijohansen) [reply src/features/form/containers/GroupContainer.tsx:277]: This is not code that is touched by this PR, so it's out of scope. If this need to be changed it could be made in another issue.
