### PR TITLE
Signee List Component

### LINKED ISSUE #2799: Layout Component for list of signees
List of signees in a signing task. 
- [ ] Should show error if configured for a task that is not "signing"
- [ ] Should show error status on a specific user if something went wrong during instance delegation
- [ ] Should show error status on a specific user if something went wrong during notification
- [ ] Should have Summary2

Figma: https://www.figma.com/design/NRczaFNKNCDcxvlMuv1WMP/Signering?node-id=877-215870&node-type=section&t=ZvabQuF9mvE87Wev-0

### PR DESCRIPTION
**Pull request by cammiida**
## Description

List of Signees to be used in `signing` task. 

Needs APIs to be updated before it works, so adding Cypress tests later.

Example view with mock data: 
image

## Related Issue(s)

- closes #2799 

## Verification/QA

- Manual functionality testing
  - [ ] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [ ] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [ ] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [ ] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [ ] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [ ] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [ ] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

File: src/language/texts/nb.ts [hunk 1]
```diff
@@ -344,6 +346,19 @@ export function nb(): FixedLanguageList {
...
       unknown_error: 'Ukjent feil. Vennligst prøv igjen senere.',
     },
+    signee_list: {
+      parse_error: 'Feil ved lasting av signatarliste.',
+      wrong_task_error: 'Denne komponenten er kun tilgjengelig i et signeringssteg.',
+      unknown_api_error: 'En feil oppstod under henting av signatarer.',
+      api_error_display: 'En feil oppstod under henting av signatarer. Se devtool-loggene for mer informasjon.',
+      signee_status_signed: 'Signert',
+      signee_status_waiting: 'Venter på signering',
+      signee_status_delegation_failed: 'Delegasjon mislyktes',
```
Comment (bjosttveit) [inline src/language/texts/nb.ts:356]: `Delegasjon` eller `Delegering`? Virker som `Delegering` kanskje er litt mer naturlig å bruke her

https://www.riksmalsforbundet.no/qa_faqs/delegasjon-eller-delegering/

Comment (cammiida) [reply src/language/texts/nb.ts:356]: Godt poeng!

File: tsconfig.json [hunk 2]
```diff
@@ -12,6 +12,7 @@
     "noEmit": true,
     "skipLibCheck": true,
     "resolveJsonModule": true,
+    "strict": true,
```
Comment (bjosttveit) [inline tsconfig.json:15]: Why is tsconfig modified here?

**Review by HauklandJ — APPROVED** [review]

File: src/layout/SigneeList/api.ts [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+  })
+  .refine(({ name, organisation }) => name || organisation, 'Either name or organisation must be present.');
+
+export type SigneeState = z.infer<typeof signeeStateSchema>;
+
+export const signeeListQuery = (partyId: string, instanceGuid: string) =>
+  queryOptions({
+    queryKey: ['signeeList', partyId, instanceGuid],
+    queryFn: () => fetchSigneeList(partyId, instanceGuid),
+    staleTime: 1000 * 60 * 10, // 10 minutes
```
Comment (bjosttveit) [inline src/layout/SigneeList/api.ts:23]: Is it important to set this explicitly? The default stale time for the query client is also 10 minutes

File: src/layout/SigneeList/SigneeListError.tsx [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+          params={[
+            'general.customer_service_phone_number',
+            'general.customer_service_email',
+            'general.customer_service_slack',
+          ].map((it, idx) => (
+            <Lang
+              key={idx}
+              id={it?.toString()}
+            />
+          ))}
```
Comment (bjosttveit) [inline src/layout/SigneeList/SigneeListError.tsx:39]: Why map a list of harcoded values instead of just harcoding the `<Lang />` components directly?

I think it should also be possible to add language references in params directly like:
```ts
params={[
  { key: 'general.customer_service_phone_number' },
  ...
]}
```

**Review by bjosttveit — APPROVED** [review]
Just have some minor comments

File: tsconfig.json (hunk 2 above)
Comment (cammiida) [reply tsconfig.json:15]: Good catch! Tror den er igjen etter jeg lekte meg litt rundt med forskjellige pakker. Fjerner 😊
