### PR TITLE
Fix edit button not showing and allow Header component in grid summary

### LINKED ISSUE #2477: Grid components with Header component references is rendered incorrectly in Summary2 components
### Description of the bug

There seem to be an issue when using a Summary2 component to with target to a Grid component. The leftmost column which is populated by header components is not rendered in the Summary2 component and neither is the Edit button in the right most column. This both makes the Summary2 component look odd and lacking in functionality. 
image

If the component reference in the Grid components left most column is changed into a text instead, both the text and the edit button will appear in the Summary2 component. 
image

### Steps To Reproduce

1. Create a Grid component where the first column contains references to Header components and the rest of the columns references to input components. 
2. Create a Summary2 component in the summary file and have it target the Grid component. 
3. Run the app and navigate to the summary page. 
4. The Summary2 component will be rendered without any text in the left most column and no edit button in the right most column.

### Additional Information

This is what the Grid component looks like with header references. 
image
It needs to be header references in order to get the hints.

### PR DESCRIPTION
**Pull request by Magnusrm**
## Description

Fixes an issue where if the first component in the row is a component without display value, the edit button is not shown and the whole row becomes uneditable.

Also allowed rendering header components in the grid-summary after request from Finanasdepartementet.

## Related Issue(s)

- closes #2477 

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [ ] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [x] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [x] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [x] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

**Review by olemartinorg — APPROVED** [review]
:raised_hands:

File: src/layout/Grid/GridSummary.tsx [hunk 1]
```diff
@@ -400,3 +406,25 @@ function CellWithLabel({ cell, columnStyleOptions, isHeader = false, headerTitle
...
+    return <Lang id={textResourceBindings.title} />;
+  } else {
+    <GenericComponent
+      node={node}
+      overrideDisplay={{
+        renderLabel: false,
+        renderLegend: false,
+        renderedInTable: true,
+      }}
+    />;
```
Comment (olemartinorg) [inline src/layout/Grid/GridSummary.tsx:428]: @Magnusrm Whoops! A little late here, but just saw this in-editor, and it lit up with warnings. Should it have returned something instead here? :thinking: Right now these lines do nothing.
