### PR TITLE
fix: fixed align tabel title

### LINKED ISSUE #4122: Tittel i tabell alignes til høyre
### Description of the bug

"Antall" som table header på kolonnen her (på repeating group med `editInTable: true` havnet til høyre, mens de andre er til venstre. Klarer ikke se hvorfor)
Image

### Steps To Reproduce

Aktuelt repo dersom dere vil se nærmere på koden: https://altinn.studio/repos/mat/akvakultur-driftsplan
Skjemaet ligger på https://mat.apps.tt02.altinn.no/mat/akvakultur-driftsplan#/Info
Dere kan bruke denne testbrukeren for å komme inn på skjemaet:

Org: 310043842 - FREDFULL GEOMETRISK TIGER AS
Daglig leder: 15892849339

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by JamalAlabdullah**
## Description

`useColumnStylesRepeatingGroups` now takes a boolean `isTitle` props, and passes it to `useTextAlignment` so header/title alignment is handled centrally in one place.
This keeps numeric right-alignment for data cells while ensuring header titles default to left unless explicitly configured via alignText.

## Related Issue(s)

- closes #4122 

Screenshot 2026-04-23 at 13 43 24

## Verification/QA

- Manual functionality testing
  - [ ] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [ ] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [ ] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [ ] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [ ] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [ ] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [ ] I have added a `kind/*` and `backport*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out
  

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed inconsistent text alignment in repeating-group table headers and titles so column headers and titles respect per-column alignment (defaults to left for title/header when appropriate).

* **Tests**
  * Added a test ensuring numeric/editable table columns render left-aligned headers to prevent regressions.

### CODE REVIEW

File: src/utils/formComponentUtils.ts [hunk 1]
```diff
@@ -145,8 +146,9 @@ export function useColumnStylesRepeatingGroups(
   }
 
   const columnCopy = { ...column };
-  columnCopy.alignText = columnCopy.alignText ?? textAlignment;
-
+  if (options?.deriveAlignmentText !== false) {
+    columnCopy.alignText = columnCopy.alignText ?? textAlignment;
+  }
```
Comment (lassopicasso) [inline src/utils/formComponentUtils.ts]: With the hardcoding `deriveAlignmentText: false` in `TitleCell` in file `RepeatingGroupTableTitle.tsx` it will never actually allow user to config the `alignText` as far as I understund. Because of `if (options?.deriveAlignmentText !== false) `

**Review by lassopicasso — COMMENTED** [review]
Nice PR, but i think this solution fix only this specific problem, and not the core problem that can lead to new problems for other cases.

I added a comment about what may be the core problem here: https://github.com/Altinn/app-frontend-react/issues/4122#issuecomment-4311680680

I would suggest take a new look on the root problem, and see if the underlying problem is in the structure in above levels where `useColumnStylesRepeatingGroups` is used.


Maybe a solution could be to pass down `isTitle:boolean` prop to `useColumnStylesRepeatingGroups` -> `useTextAlignment` could solve this, and keep the styling logic in `useTextAlignment` instead of adding extra styling other places that is harder to maintain later.
```
function useTextAlignment(baseComponentId: string, isTitle: boolean): 'left' | 'center' | 'right' {
  const component = useLayoutLookups().getComponent(baseComponentId);
  const formatting = component.type === 'Input' ? component.formatting : undefined;
  if (!formatting || && isTitle) {
    return 'left';
  }
  if (formatting.align) {
    return formatting.align;
  }
  return formatting.number ? 'right' : 'left';
}

```

What do you think?

**Comment by olemartinorg** [comment]
@lassopicasso That seems like a good solution to me - it looks to be a very targeted fix that won't affect anything else. :raised_hands:

File: src/utils/formComponentUtils.ts (hunk 1 above)
Comment (JamalAlabdullah) [reply src/utils/formComponentUtils.ts]: I guess passing the props as you suggested is better 👍

Comment (lassopicasso) [reply src/utils/formComponentUtils.ts]: Yeah, I think that is cleaner and more safe.

File: src/layout/RepeatingGroup/Table/RepeatingGroupTableTitle.tsx [hunk 2]
```diff
@@ -16,7 +16,7 @@ interface IProps {
 }
 
 export const RepeatingGroupTableTitle = ({ baseComponentId, columnSettings }: IProps) => {
-  const style = useColumnStylesRepeatingGroups(baseComponentId, columnSettings);
+  const style = useColumnStylesRepeatingGroups(baseComponentId, columnSettings, { isTitle: true });
```
Comment (lassopicasso) [inline src/layout/RepeatingGroup/Table/RepeatingGroupTableTitle.tsx]: is it a reason for passing it down as a object with a prop, and not just a single prop itself?

File: src/utils/formComponentUtils.ts [hunk 3]
```diff
@@ -137,16 +137,17 @@ function useTextAlignment(baseComponentId: string): 'left' | 'center' | 'right'
 export function useColumnStylesRepeatingGroups(
   baseComponentId: string,
   columnSettings: IGroupColumnFormatting | undefined,
+  options?: { isTitle?: boolean },
```
Comment (lassopicasso) [inline src/utils/formComponentUtils.ts]: Since this is the only prop and options is new param, I would keep the new param as a boolean instead of a object with a boolean, and keep the same name for consistent: `isTitle` instead of `options`

**Review by lassopicasso — COMMENTED** [review]
Nice, a few comments to simplify the new param

**Review by lassopicasso — APPROVED** [review]
🥳 
@JamalAlabdullah great job, you can merge it now when tests run green
