### PR TITLE
Selected Language stored in localstorage should be saved per user

### LINKED ISSUE #1005: Selected Language stored in localstorage should be saved per user.
### Description of the bug

Language preference should be stored per user and should not be shared.

### Bakground
When multiple users are taking a survey on a public computer it is highly likely users have different language preferences. The language one user picks should not change the default for another user.

### Steps To Reproduce

1. Log in as user 1
2. Change language
3. Log inn as a different user
4. The selected language should be default but is the same as the first user language

### Additional Information

I suggest changing the localStorage key to include a unique key for the user

### PR DESCRIPTION
**Pull request by lasseklovstad**
## Description
selectedAppLanguage state is moved to profileState in Redux store (It made more sense to me). When the selectedAppLanguage is changed the language is saved to localStorage as before. BUT the localStorage key include the userId (New). 

I believe this is a breaking change for the users who has changed their language (For them it will default back to profile preferences). 

## Related Issue(s)

- closes #1005

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [x] Unit test(s) have been added/updated
  - [x] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [x] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [x] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Changes/additions to component properties
  - [ ] Changes are reflected in both `src/layout/layout.d.ts` and `layout.schema.v1.json`, and these are all backwards-compatible
  - [x] No changes made
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [x] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

File: src/shared/resources/profile/profileSlice.ts [hunk 1]
```diff
@@ -7,14 +10,23 @@ import type {
...
+const altinnWindow = window as Window as IAltinnWindow;
+const getLanguageStorageKey = (userId: number | undefined) => `selectedAppLanguage${altinnWindow.app}${userId ?? ''}`;
+
+export const initialState: IProfileState = {
   profile: {
     profileSettingPreference: {
       language: 'nb',
     },
   } as IProfile,
+  selectedAppLanguage: '',
```
Comment (lasseklovstad) [inline src/shared/resources/profile/profileSlice.ts:29]: Maybe the default language should be:
```suggestion
  selectedAppLanguage: getLanguageStorageKey(undefined),
```
This will then support remembering the selected language for stateless app (no user logg in). But is it neccassary to store the selected language for a stateless? Maybe it is better to store this in sessionStorage...

Comment (framitdavid) [reply src/shared/resources/profile/profileSlice.ts]: First of all, thanks for your great contribution.  🚀 I agree with you that we should use "`getLanguageStorageKey(undefined)`" to persist the selected language on stateless apps. It's more of a nice-to-have feature than a need-to-have for stateless apps if you ask me.

Since the user is not logged in and we do not know if the next user is the same person, it might make sense to persist this within session storage instead of local storage to ensure other persons/users get the default language.

Within this PR I think it's good enough **not** persist the language within stateless apps. Because if we set the key `selectedAppLanguage${altinnWindow.app}` and later on move this to session storage, we need to write logic to clean up local storage by removing the key.  :)

Comment (lasseklovstad) [reply src/shared/resources/profile/profileSlice.ts]: I agree. It makes sense not to save it to localStorage if no user is logged inn.

**Review by framitdavid — APPROVED** [review]
🚀 🥇
